name: Bug Report
description: Report a bug, crash, or other type of error in SRB2 Mod Profile Manager
type: Bug
body:
  - id: validation
    type: checkboxes
    attributes:
      label: Validation
      options:
      - label: I have checked the [Issues](https://github.com/WasAMudkip/SRB2ProfileManager/issues) page to see if my problem has already been reported
        required: true
  - id: mods-used
    type: textarea
    validations:
      required: false
    attributes:
      label: Addons used, if any.
      description: If you can, provide a list of the addons used while running SRB2MPM.
  - id: describe-bug
    type: textarea
    validations:
      required: true
    attributes:
      label: Describe the Bug
      description: A clear and concise description of what the bug is.
  - id: repro-steps
    type: textarea
    validations:
      required: true
    attributes:
      label: Steps to Reproduce
      description: Step-by-step instructions on how to reproduce the bug.
      placeholder: |
        1. Go to '...'
        2. etc.
  - id: expected-behavior
    type: textarea
    validations:
      required: true
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
  - id: footage
    type: textarea
    validations:
      required: false
    attributes:
      label: Footage
      description: Attach a screenshot or video of the bug if possible.
  - id: specs-version
    type: input
    validations:
      required: true
    attributes:
      label: Version
      description: The version of SRB2MPM you are using. This can be found at the top of the window.
  - id: specs-os
    type: input
    validations:
      required: true
    attributes:
      label: Operating System
      description: The name of the operating system you are running (e.g. **Windows 10**, **Windows 11**, **Linux distro**).
  - id: additional-context
    type: textarea
    validations:
      required: false
    attributes:
      label: Additional Context
      description: Provide any additional context about the bug if you can.
