name: Build

on:
  push:
    branches: [ "main" ]
    paths:
      - 'src/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          if (Test-Path requirements.txt) { pip install -r requirements.txt }

      - name: Build
        run: |
          pyinstaller --onefile --console --paths src --name srb2profilemanager src/main.py

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: srb2profilemanager
          path: dist/srb2profilemanager.exe
          if-no-files-found: error
